version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=db
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - PGPORT=${PGPORT}
      - DBDIALECT=${DBDIALECT}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
      - AWS_PUBLIC_KEY=${AWS_PUBLIC_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - HOSTEMAIL=${HOSTEMAIL}
      - SMTPPORT=${SMTPPORT}
      - SECURE=${SECURE}
      - USERSMTP=${USERSMTP}
      - PASSSMTP=${PASSSMTP}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis
      - migrate
    command: npm run dev

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

  migrate:
    build: .
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGHOST=db
      - PGPORT=${PGPORT}
      - DBDIALECT=${DBDIALECT}
    depends_on:
      - db
    command: npm run db:migrate

volumes:
  postgres-data:
  redis-data:
